name: Build/Artifact
on: [push, pull_request, workflow_dispatch]

jobs:
  publish:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 6.0
      uses: actions/setup-dotnet@v1
      with:
         dotnet-version: 6.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1

    - name: publish
      run: |
          dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true --self-contained true
      
    - name: Upload an Artifacts
      uses: actions/upload-artifact@v2.2.4
      with:
          name: Scraper
          path: ./WebScraperDevOps/bin/Debug/net6.0/win-x64/publish/**.exe
